query CoinMeta2ById($id: Int64!) @auth(level: PUBLIC, insecureReason: "Anyone can query coins publicly") {
    coinMetas2s(where: { id: { eq: $id }}) {
        id muisId ref name date material diameter region nomValue lemmaName
    }
}

query CoinById($id: Int64!) @auth(level: PUBLIC, insecureReason: "Anyone can query coins publicly") {
    coinMetas(where: { id: { eq: $id }}) {
        id muisId title description date diameterMm
    }
}