name: e2e-test-android

on:
  pull_request:
    branches: ['*'] # Run the E2E test workflow on every pull/merge request.
jobs:
  build_android_for_e2e:
    type: build
    params:
      platform: android
      profile: e2e-test

  maestro_test:
    needs: [build_android_for_e2e]
    type: maestro-cloud
    params:
      build_id: ${{ needs.build_android_for_e2e.outputs.build_id }}
      flows: '.maestro/uc-1-tests/, .maestro/uc-2-tests/, .maestro/uc-4-tests/, .maestro/uc-5-tests/, .maestro/uc-6-tests/, .maestro/uc-7-tests/'
      maestro_project_id: $MAESTRO_API_KEY