type CoinMetas2 @table(key: ["id"]) {
    id: Int64! @col(dataType: "bigserial")
    muisId: Int64!
    ref: String!
    name: String!
    date: String
    material: String
    diameter: Float! @col(dataType: "numeric")
    region: String
    nomValue: String
    lemmaName: String
    dateCluster: String
}

type CoinMeta @table(key: ["muisId"]) {
    id: Int64! @col(dataType: "bigserial")
    muisId: Int!
    title: String!
    date: String
    description: String
    diameterMm: Float! @col(dataType: "real") @default(expr: "0.0")
}