type CoinMetas2 @table(key: ["muisId"]) {
    id: Int64! @col(dataType: "bigserial")
    muisId: Int64!
    ref: String!
    name: String!
    date: String
    material: String
    diameter: Float!
    region: String
    nomValue: String
    lemmaName: String
}